# Generated by Django 4.2.20 on 2025-03-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
