# Generated by Django 4.2.20 on 2025-03-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_review_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="description", new_name="comment",
        ),
    ]
