# Generated by Django 4.2.20 on 2025-03-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="image",),
    ]
