# Generated by Django 4.2.20 on 2025-03-10 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_review"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem", unique_together={("cart", "product")},
        ),
    ]
