# Generated by Django 4.2.20 on 2025-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
